# Generated by Django 4.2.20 on 2025-03-27 07:14
#
# Original operation: RenameIndex(old_fields=("id","email"), new_name="user_id_email_idx")
# Skipped because 0001_initial already created the index with this name,
# causing a duplicate CREATE INDEX during SQLite _remake_table in later migrations.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nexapp_users", "0020_populate_password_updated_field"),
    ]

    operations = []
