# Generated by Django 4.2.16 on 2026-02-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexapp_users", "0021_rename_user_id_email_openwisp_us_id_06c07a_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="require_2fa",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user is forced to set up Two-Factor Authentication.",
                verbose_name="Require 2FA",
            ),
        ),
    ]
